version: '3.3'

services:
  build_app:
    build:
      context: build_app/
      args:
        package_folder: ${package_folder}
        war_folder: ${war_folder}
    volumes:
      - javaappvol:${war_folder}

  deploy_app:
    image: tomcat:jre8-alpine
    ports:
      - "8080:8080"
    volumes:
      - javaappvol:/usr/local/tomcat/webapps
    depends_on:
      - build_app
volumes:
  javaappvol:


