version: '3.3'

services:
  build_app:
    build:
      context: build_app/
      args:
        package_folder: ${package_folder}
        war_folder: ${war_folder}
        config_folder: ${config_folder}
    volumes:
      - javaappvol:${war_folder}
      - configvol:${config_folder}

  db:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      app_net:
        ipv4_address: 172.20.0.10
    ports:
      - "3306:3306"
    depends_on:
      - build_app

  deploy_app:
    image: tomcat:6.0-jre8
    restart: always
    networks:
      app_net:
        ipv4_address: 172.20.0.20
    ports:
      - "8080:8080"
    volumes:
      - javaappvol:/usr/local/tomcat/webapps
      - configvol:/usr/local/tomcat/ROOT
    depends_on:
      - build_app
      - db

volumes:
  javaappvol:
  configvol:

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24


